source 'https://rubygems.org'
gem 'jekyll', '~> 4.3.3'
gem 'webrick', '~> 1.8'
gem 'jekyll-sass-converter', '~> 3.0'
gem 'jekyll-watch', '~> 2.2'
gem 'jekyll-seo-tag'
gem 'jekyll-gist'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'kramdown-parser-gfm'
