name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main # Change this to your default branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Remove problematic files
        run: |
          rm -rf ./login-backend/node_modules/balanced-match/README.md
          rm -rf ./login-backend/node_modules/@mapbox/node-pre-gyp/CHANGELOG.md
          rm -rf ./login-backend/node_modules/accepts/HISTORY.md
          rm -rf ./login-backend/node_modules/aproba/CHANGELOG.md
          rm -rf ./login-backend/node_modules/bcrypt/CHANGELOG.md
          rm -rf ./login-backend/node_modules/bcrypt/SECURITY.md
          rm -rf ./login-backend/node_modules/body-parser/HISTORY.md
          rm -rf ./login-backend/node_modules/body-parser/SECURITY.md
          rm -rf ./login-backend/node_modules/bytes/History.md
          rm -rf ./login-backend/node_modules/call-bind/CHANGELOG.md
          find ./node_modules -type f -name "*.md" -delete
          find ./login-backend/node_modules -type f -name "*.md" -delete

      - name: Install dependencies
        run: |
          gem install jekyll bundler
          bundle install

      - name: Build site
        run: bundle exec jekyll build --config _config.yml --future --drafts

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
